direction: up

sub -> ac
ac -> bf

bf: <<interface>>\nBeanFactory {
    style.border-radius: 10
}
ac: <<interface>>\nApplicationContext {
    style.border-radius: 10
}
sub: AnnotationConfig\nApplicationContext {
    style.border-radius: 10
}
