###
POST http://localhost:8080/mapping-produce
Accept: */*

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

###
POST http://localhost:8080/mapping-produce
Accept: application/json

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

